# Generated by Django 5.2.2 on 2025-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_customuser_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='admitido',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.CharField(blank=True, choices=[('Historia', 'Historia'), ('Bellas Artes', 'Bellas Artes'), ('Antropología', 'Antropología')], max_length=50, null=True),
        ),
    ]
